runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS : /home/utkarsh1/Documents/cloud-storage-key.json